FROM tomcat:10.1-jdk11-openjdk-slim
COPY target/my-final.war /usr/local/tomcat/webapps/
EXPOSE 8080

# FROM tomcat:9.0.59-jdk11-openjdk
# COPY target/my-app.war /usr/local/tomcat/webapps/
# EXPOSE 8080
# CMD ["catalina.sh", "run"]