version: '3'
services:
  java-rest-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - mynetwork

  frontend:
    image: node:14
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    command: sh -c "npm install && npm start"
    ports:
      - "3000:3000"
    networks:
      - mynetwork

networks:
  mynetwork:
